"""added categories,products and reviews

Revision ID: 014a1dc5b5e8
Revises: a9b702b68fbe
Create Date: 2026-07-20 21:31:05.111934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014a1dc5b5e8'
down_revision: Union[str, Sequence[str], None] = 'a9b702b68fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
