"""added on delete cascade and on update cascade

Revision ID: 457e24737438
Revises: 3f52bec7d752
Create Date: 2026-07-22 20:16:01.647967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457e24737438'
down_revision: Union[str, Sequence[str], None] = '3f52bec7d752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_product_id_fkey'), 'cart', type_='foreignkey')
    op.drop_constraint(op.f('cart_user_id_fkey'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'cart', 'product', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(None, 'order', ['id'])
    op.drop_constraint(op.f('order_rider_id_fkey'), 'order', type_='foreignkey')
    op.drop_constraint(op.f('order_customer_id_fkey'), 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['customer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'order', 'rider', ['rider_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('order_item_product_id_fkey'), 'order_item', type_='foreignkey')
    op.drop_constraint(op.f('order_item_order_id_fkey'), 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'order_item', 'product', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key(op.f('order_item_order_id_fkey'), 'order_item', 'order', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_item_product_id_fkey'), 'order_item', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(op.f('order_customer_id_fkey'), 'order', 'user', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('order_rider_id_fkey'), 'order', 'rider', ['rider_id'], ['id'])
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_user_id_fkey'), 'cart', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('cart_product_id_fkey'), 'cart', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
