"""created rider table

Revision ID: 840d9db22faf
Revises: 1da999a74db7
Create Date: 2026-07-22 01:03:06.171150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840d9db22faf'
down_revision: Union[str, Sequence[str], None] = '1da999a74db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rider', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rider', type_='unique')
    # ### end Alembic commands ###
