"""created product and review tables

Revision ID: a9b702b68fbe
Revises: e960fff62f67
Create Date: 2026-07-20 21:16:42.538303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b702b68fbe'
down_revision: Union[str, Sequence[str], None] = 'e960fff62f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'review', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    # ### end Alembic commands ###
